/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author еркыпе
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        MainJPanel = new javax.swing.JPanel();
        ThermalConductivityRB = new javax.swing.JRadioButton();
        HeatTransferRB = new javax.swing.JRadioButton();
        InfiltrationRB = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        HelpMenu = new javax.swing.JMenu();
        MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Потери теплоты в зданиях и сооружениях ");
        setPreferredSize(new java.awt.Dimension(900, 850));
        setResizable(false);

        MainJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainJPanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);
        MainJPanel.setLayout(MainJPanelLayout);
        MainJPanelLayout.setHorizontalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        MainJPanelLayout.setVerticalGroup(
            MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        buttonGroup.add(ThermalConductivityRB);
        ThermalConductivityRB.setText("Теплопроводность");
        ThermalConductivityRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThermalConductivityRBActionPerformed(evt);
            }
        });

        buttonGroup.add(HeatTransferRB);
        HeatTransferRB.setText("Теплопередача");
        HeatTransferRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeatTransferRBActionPerformed(evt);
            }
        });

        buttonGroup.add(InfiltrationRB);
        InfiltrationRB.setText("Инфильтрация");
        InfiltrationRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfiltrationRBActionPerformed(evt);
            }
        });

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        outputArea.setLineWrap(true);
        outputArea.setRows(5);
        outputArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Вывод"));
        jScrollPane2.setViewportView(outputArea);

        HelpMenu.setText("Помощь");

        MenuItem.setText("Методические указания");
        MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(MenuItem);
        MenuItem.getAccessibleContext().setAccessibleName("Методичка");

        MenuBar.add(HelpMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ThermalConductivityRB)
                .addGap(18, 18, 18)
                .addComponent(InfiltrationRB)
                .addGap(18, 18, 18)
                .addComponent(HeatTransferRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThermalConductivityRB)
                    .addComponent(HeatTransferRB)
                    .addComponent(InfiltrationRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
        // Окно с методическими указаниями
        SwingController controller = new SwingController();
        SwingViewBuilder factory = new SwingViewBuilder(controller);
        JPanel VievComponentPanel = factory.buildViewerPanel();
        controller.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                        controller.getDocumentViewController()));
        JFrame pdfFrame = new JFrame("Методические указания");
        pdfFrame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        pdfFrame.add(VievComponentPanel);
        controller.openDocument(filePath);
        pdfFrame.pack();
        pdfFrame.setSize(900, 800);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - pdfFrame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - pdfFrame.getHeight()) / 2);
        pdfFrame.setLocation(x, y);
        pdfFrame.setVisible(true);
    }//GEN-LAST:event_MenuItemActionPerformed

    private void InfiltrationRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfiltrationRBActionPerformed
        //  Инфильтрация 
        MainJPanel.removeAll();
        // Инициализация и объявление элементов
        JLabel lyamdaLabel = new JLabel("λ – коэффициент теплопроводности стенки (зависит от материала и характеризует его способность проводить тепло, Вт/(м·К)");
        JLabel deltaLabel = new JLabel("δ – толщина стенки, м");
        JLabel mLabel = new JLabel("m – кратность воздухообмена помещения объемом Vп за 1 ч");
        JLabel VInLabel = new JLabel("Vп – объём помещения, м^3");
        JLabel fLabel = new JLabel("F – площадь стенки, м 2");
        JLabel alphaInLabel = new JLabel("αв – коэффициент теплоотдачи воздуха со стороны помещения, Вт/(м/2·К)");
        JLabel alphaOutLabel = new JLabel("αн – коэффициент теплоотдачи наружного воздуха, Вт/(м/2·К)");
        JLabel tInjLabel = new JLabel("tв – температура внутренней поверхности стенки, °С");
        JLabel tOutLabel = new JLabel("tн – температура наружной поверхности стенки, °С");

        JTextField lyambda = new JTextField();
        lyambda.setText("0");
        JTextField delta = new JTextField();
        delta.setText("0");
        JTextField m = new JTextField();
        m.setText("0");
        JTextField VIn = new JTextField();
        VIn.setText("0");
        JTextField f = new JTextField();
        f.setText("0");
        JTextField alphaIn = new JTextField();
        alphaIn.setText("0");
        JTextField alphaOut = new JTextField();
        alphaOut.setText("0");
        JTextField tIn = new JTextField();
        tIn.setText("0");
        JTextField tOut = new JTextField();
        tOut.setText("0");

        JButton computeButton = new JButton();
        computeButton.setText("Вычислить");
        computeButton.addActionListener(new ActionListener() {
            @Override
            // Нажатие на кнопку "Вычислить"
            public void actionPerformed(ActionEvent e) {
                try {
                    // Основные вычисление
                    double result = ((Math.pow((1 / Double.parseDouble(alphaIn.getText()))
                            + (Double.parseDouble(lyambda.getText()) / Double.parseDouble(delta.getText()))
                            + (1 / Double.parseDouble(alphaOut.getText())), -1) * Double.parseDouble(f.getText()))
                            + (((Double.parseDouble(m.getText())) * Double.parseDouble(VIn.getText())) / 3))
                            * (Double.parseDouble(tIn.getText()) - Double.parseDouble(tOut.getText()));
                    // Отображение результата вычисления
                    outputArea.setText("Входные параметры: \n" + tIn.getText() + " и " + tOut.getText()
                            + " – температура внутренней и наружной поверхности"
                            + "стенки, °С; " + lyambda.getText() + " – коэффициент теплопроводности стенки (зависит от"
                            + "материала и характеризует его способность проводить тепло,"
                            + "Вт/(м·К); " + delta.getText() + " – толщина стенки, м; R = δ / λ – термическое сопротивление стенки, (м^2"
                            + "·К)/Вт; " + f.getText() + " – площадь стенки, м^2; " + alphaIn.getText() + " – коэффициент теплоотдачи воздуха со стороны помещения; "
                            + alphaOut.getText() + " – коэффициент теплоотдачи наружного воздуха, Вт/(м/2); " + m.getText() + " – кратность воздухообмена помещения объемом Vп за 1 ч; "
                            + alphaOut.getText() + " – объем помещения, м^3.");
                    String formattedResult = String.format("%.4f", result);
                    outputArea.append("\nВывод: \nПлотность теплового потока по заданым данным равна: " + formattedResult);
                } catch (NumberFormatException ex) {
                    // Отображение исключения в его случае  
                    outputArea.append("\nВывод: Ошибка ввода. Неверный формат: " + ex.getMessage());
                }
            }
        });
        
        //  Расположение элементов
        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);

        MainJPanel.setLayout(MainJPanelLayout);

        MainJPanelLayout.setHorizontalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lyamdaLabel)
                                        .addComponent(deltaLabel)
                                        .addComponent(mLabel)
                                        .addComponent(VInLabel)
                                        .addComponent(fLabel)
                                        .addComponent(alphaInLabel)
                                        .addComponent(alphaOutLabel)
                                        .addComponent(tInjLabel)
                                        .addComponent(tOutLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(delta)
                                        .addComponent(lyambda)
                                        .addComponent(m)
                                        .addComponent(VIn)
                                        .addComponent(f)
                                        .addComponent(alphaIn)
                                        .addComponent(alphaOut)
                                        .addComponent(tIn)
                                        .addComponent(tOut)
                                        .addComponent(computeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        MainJPanelLayout.setVerticalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lyambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lyamdaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deltaLabel)
                                        .addComponent(delta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(VInLabel)
                                        .addComponent(VIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fLabel)
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alphaInLabel)
                                        .addComponent(alphaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alphaOutLabel)
                                        .addComponent(alphaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tInjLabel)
                                        .addComponent(tIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tOutLabel)
                                        .addComponent(tOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(computeButton))
        );

        MainJPanel.repaint();
    }//GEN-LAST:event_InfiltrationRBActionPerformed

    private void ThermalConductivityRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThermalConductivityRBActionPerformed
        // Теплопроводность через однослойную и многослойную плоскую стенку 
        MainJPanel.removeAll();
        // Инициализация и объявление элементов
        JLabel lyamdaLabel = new JLabel("λ – коэффициент теплопроводности первой стенки (зависит от материала и характеризует его способность проводить тепло, Вт/(м·К)");
        JLabel deltaLabel = new JLabel("δ – толщина первой стенки, м");
        JLabel fLabel = new JLabel("F – площадь стенки, м 2");
        JLabel tInjLabel = new JLabel("tв – температура внутренней поверхности стенки, °С");
        JLabel tOutLabel = new JLabel("tн – температура наружной поверхности стенки, °С");

        JTextField lyambda = new JTextField();
        lyambda.setText("0");
        JTextField delta = new JTextField();
        delta.setText("0");
        JTextField f = new JTextField();
        f.setText("0");
        JTextField tIn = new JTextField();
        tIn.setText("0");
        JTextField tOut = new JTextField();
        tOut.setText("0");

        JButton computeButton = new JButton();
        computeButton.setText("Вычислить");
        computeButton.addActionListener(new ActionListener() {
            @Override
            // Нажатие на кнопку вычислить 
            public void actionPerformed(ActionEvent e) {
                try {
                    // Вычисление результата
                    double result = Double.parseDouble(lyambda.getText()) / Double.parseDouble(delta.getText())
                            * (Double.parseDouble(tIn.getText()) - Double.parseDouble(tOut.getText())) * Double.parseDouble(f.getText());
                    // Отображение результата вычисления
                    outputArea.setText("Входные параметры: \n" + tIn.getText() + " и " + tOut.getText()
                            + " – температура внутренней и наружной поверхности"
                            + "стенки, °С; " + lyambda.getText() + " – коэффициент теплопроводности стенки (зависит от"
                            + "материала и характеризует его способность проводить тепло,"
                            + "Вт/(м·К); " + delta.getText() + " – толщина стенки, м; R = δ / λ – термическое сопротивление стенки, (м^2"
                            + "·К)/Вт; " + f.getText() + " – площадь стенки, м^2.");
                    String formattedResult = String.format("%.4f", result);
                    outputArea.append("\nВывод: \nОбщая тепловые потери через однослойную плоскую стенку равна: " + formattedResult);
                } catch (NumberFormatException ex) {
                    // Отображение исключения в его случае
                    outputArea.append("\nВывод: Ошибка ввода. Неверный формат: " + ex.getMessage());
                }
            }
        });

        // Расположение элементов
        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);

        MainJPanel.setLayout(MainJPanelLayout);

        MainJPanelLayout.setHorizontalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lyamdaLabel)
                                        .addComponent(deltaLabel)
                                        .addComponent(fLabel)
                                        .addComponent(tInjLabel)
                                        .addComponent(tOutLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(delta)
                                        .addComponent(lyambda)
                                        .addComponent(f)
                                        .addComponent(tIn)
                                        .addComponent(tOut)
                                        .addComponent(computeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        MainJPanelLayout.setVerticalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lyambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lyamdaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deltaLabel)
                                        .addComponent(delta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fLabel)
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tInjLabel)
                                        .addComponent(tIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tOutLabel)
                                        .addComponent(tOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(computeButton))
        );

        MainJPanel.repaint();

    }//GEN-LAST:event_ThermalConductivityRBActionPerformed

    private void HeatTransferRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeatTransferRBActionPerformed
        // Теплопередача через многослойную плоскую стенку. В данном случае три слоя.
        MainJPanel.removeAll();
        // Инициализация и объявление элементов
        JLabel lyamdaLabel = new JLabel("λ – коэффициент теплопроводности первой стенки (зависит от материала и характеризует \n"
                + "его способность проводить тепло, Вт/(м·К)");
        JLabel deltaLabel = new JLabel("δ – толщина первой стенки, м");
        JLabel lyamdaLabel2 = new JLabel("λ – коэффициент теплопроводности второй стенки (зависит от материала и характеризует \n"
                + "его способность проводить тепло, Вт/(м·К)");
        JLabel deltaLabel2 = new JLabel("δ – толщина второй стенки, м");
        JLabel lyamdaLabel3 = new JLabel("λ – коэффициент теплопроводности третьей стенки (зависит от материала и характеризует \n"
                + "его способность проводить тепло, Вт/(м·К)");
        JLabel deltaLabel3 = new JLabel("δ – толщина третьей стенки, м");
        JLabel fLabel = new JLabel("F – площадь стенки, м 2");
        JLabel alphaInLabel = new JLabel("αв – коэффициент теплоотдачи воздуха со стороны помещения, Вт/(м/2·К)");
        JLabel alphaOutLabel = new JLabel("αн – коэффициент теплоотдачи наружного воздуха, Вт/(м/2·К)");
        JLabel tInjLabel = new JLabel("tв – температура внутренней поверхности стенки, °С");
        JLabel tOutLabel = new JLabel("tн – температура наружной поверхности стенки, °С");

        JTextField lyambda = new JTextField();
        lyambda.setText("0");
        JTextField delta = new JTextField();
        delta.setText("0");
        JTextField lyambda2 = new JTextField();
        lyambda2.setText("0");
        JTextField delta2 = new JTextField();
        delta2.setText("0");
        JTextField lyambda3 = new JTextField();
        lyambda3.setText("0");
        JTextField delta3 = new JTextField();
        delta3.setText("0");
        JTextField f = new JTextField();
        f.setText("0");
        JTextField alphaIn = new JTextField();
        alphaIn.setText("0");
        JTextField alphaOut = new JTextField();
        alphaOut.setText("0");
        JTextField tIn = new JTextField();
        tIn.setText("0");
        JTextField tOut = new JTextField();
        tOut.setText("0");

        JButton computeButton = new JButton();
        computeButton.setText("Вычислить");
        computeButton.addActionListener(new ActionListener() {
            @Override // Метод на кноопку вычислить 
            public void actionPerformed(ActionEvent e) {
                try {
                    // Вычисление результата
                    double result = Math.pow((1 / Double.parseDouble(alphaIn.getText()))
                            + ((Double.parseDouble(delta.getText()) / Double.parseDouble(lyambda.getText()))
                            + (Double.parseDouble(delta2.getText()) / Double.parseDouble(lyambda2.getText()))
                            + (Double.parseDouble(delta3.getText()) / Double.parseDouble(lyambda3.getText())))
                            + (1 / Double.parseDouble(alphaOut.getText())), -1)
                            * (Double.parseDouble(tIn.getText()) - Double.parseDouble(tOut.getText())) * Double.parseDouble(f.getText());

                    double R = (Double.parseDouble(delta.getText()) / Double.parseDouble(lyambda.getText()))
                            + (Double.parseDouble(delta2.getText()) / Double.parseDouble(lyambda2.getText()))
                            + (Double.parseDouble(delta3.getText()) / Double.parseDouble(lyambda3.getText()));
                    
                    // Отображение результата вычисления
                    outputArea.setText("Входные параметры: \n" + tIn.getText() + " и " + tOut.getText()
                            + " – температура внутренней и наружной поверхности"
                            + "стенки, °С; " + R + " – R = δ / λ – термическое сопротивление стенок, (м^2"
                            + "·К)/Вт; " + f.getText() + " – площадь стенки, м^2; " + alphaIn.getText() + " – коэффициент теплоотдачи воздуха со стороны помещения; "
                            + alphaOut.getText() + " – коэффициент теплоотдачи наружного воздуха, Вт/(м/2).");
                    String formattedResult = String.format("%.4f", result);
                    outputArea.append("\nВывод: \nТеплопередачи через двуслойную плоскую стенкуравна: " + formattedResult);
                } catch (NumberFormatException ex) {
                    // Отображение исключения в его случае
                    outputArea.append("\nВывод: Ошибка ввода. Неверный формат: " + ex.getMessage());
                }
            }
        });
        
        // Расположение компонентов 
        javax.swing.GroupLayout MainJPanelLayout = new javax.swing.GroupLayout(MainJPanel);

        MainJPanel.setLayout(MainJPanelLayout);

        MainJPanelLayout.setHorizontalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lyamdaLabel)
                                        .addComponent(deltaLabel)
                                        .addComponent(lyamdaLabel2)
                                        .addComponent(deltaLabel2)
                                        .addComponent(lyamdaLabel3)
                                        .addComponent(deltaLabel3)
                                        .addComponent(fLabel)
                                        .addComponent(alphaInLabel)
                                        .addComponent(alphaOutLabel)
                                        .addComponent(tInjLabel)
                                        .addComponent(tOutLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(delta)
                                        .addComponent(lyambda)
                                        .addComponent(delta2)
                                        .addComponent(lyambda2)
                                        .addComponent(delta3)
                                        .addComponent(lyambda3)
                                        .addComponent(f)
                                        .addComponent(alphaIn)
                                        .addComponent(alphaOut)
                                        .addComponent(tIn)
                                        .addComponent(tOut)
                                        .addComponent(computeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        MainJPanelLayout.setVerticalGroup(
                MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainJPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lyambda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lyamdaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deltaLabel)
                                        .addComponent(delta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lyambda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lyamdaLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deltaLabel2)
                                        .addComponent(delta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lyambda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lyamdaLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deltaLabel3)
                                        .addComponent(delta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fLabel)
                                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alphaInLabel)
                                        .addComponent(alphaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alphaOutLabel)
                                        .addComponent(alphaOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tInjLabel)
                                        .addComponent(tIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tOutLabel)
                                        .addComponent(tOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(computeButton))
        );

        MainJPanel.repaint();
    }//GEN-LAST:event_HeatTransferRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton HeatTransferRB;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JRadioButton InfiltrationRB;
    private javax.swing.JPanel MainJPanel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JRadioButton ThermalConductivityRB;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea outputArea;
    // End of variables declaration//GEN-END:variables
    private String filePath = "D:\\Projects\\Heat_loss_in_buildings_and_structures\\Heat_loss_in_buildings_and_structures"
            + "\\res\\Jenergosberezhenie_Dmitrichenko_2018.docx"; 
}
